langchain4j:
  community:
    dashscope:
      chat-model: # 阻塞调用配置
        api-key: ${ANTHROPIC_AUTH_TOKEN}
        model-name: qwen3-max
      streaming-chat-model: # 流式调用配置
        api-key: ${ANTHROPIC_AUTH_TOKEN}
        model-name: qwen3-max